/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import excepciones.MyException;
import gestores.GestorDB;
import javax.swing.JOptionPane;

/**
 *
 * @author ivanramonbolsa
 */
public class WAltaMod extends javax.swing.JFrame {

    /**
     * Creates new form WAltaMod
     */
    private MainWindow w;
    private GestorDB myDB;
    private String sqlErrorLog;
    public WAltaMod(MainWindow w, GestorDB myDB, boolean mod, String sqlErrorLog) {
        this.w = w;
        this.myDB = myDB;
        this.sqlErrorLog = sqlErrorLog;
        initComponents();
        initMod(mod);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void initMod(boolean mod){
        if (mod) {
            btnEnviar.setVisible(false);
            btnEnviar.setEnabled(false);
            btnMod.setEnabled(true);
            btnMod.setVisible(true);
            etTitle.setText("EDITAR ARTICULO");
            descField.setEnabled(false);
            precioField.setEnabled(false);
            stockField.setEnabled(false);
            this.setVisible(true);
        }else{
            btnEnviar.setVisible(true);
            btnEnviar.setEnabled(true);
            btnMod.setEnabled(false);
            btnMod.setVisible(false);
            etTitle.setText("ALTA ARTICULO");
            descField.setEnabled(true);
            precioField.setEnabled(true);
            stockField.setEnabled(true);
            this.setVisible(true);
        }
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        etTitle = new javax.swing.JLabel();
        etCod = new javax.swing.JLabel();
        codField = new javax.swing.JTextField();
        etDesc = new javax.swing.JLabel();
        descField = new javax.swing.JTextField();
        etPrecio = new javax.swing.JLabel();
        precioField = new javax.swing.JTextField();
        etStock = new javax.swing.JLabel();
        stockField = new javax.swing.JTextField();
        btnExit = new javax.swing.JButton();
        btnEnviar = new javax.swing.JButton();
        btnMod = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        etTitle.setFont(new java.awt.Font("Apple SD Gothic Neo", 1, 24)); // NOI18N
        etTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etTitle.setText("ALTA");
        jPanel1.add(etTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(-1, 20, 400, -1));

        etCod.setText("cod_art ");
        jPanel1.add(etCod, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 73, -1, -1));

        codField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codFieldActionPerformed(evt);
            }
        });
        jPanel1.add(codField, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 68, 249, -1));

        etDesc.setText("descripción");
        jPanel1.add(etDesc, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 105, -1, -1));
        jPanel1.add(descField, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 100, 249, -1));

        etPrecio.setText("precio ");
        jPanel1.add(etPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 137, -1, -1));
        jPanel1.add(precioField, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 132, 249, -1));

        etStock.setText("stock ");
        jPanel1.add(etStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 169, -1, -1));

        stockField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stockFieldActionPerformed(evt);
            }
        });
        jPanel1.add(stockField, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 164, 249, -1));

        btnExit.setText("Volver");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        jPanel1.add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 210, -1, -1));

        btnEnviar.setText("Alta");
        btnEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEnviar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, -1, -1));

        btnMod.setText("Modificar");
        btnMod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModActionPerformed(evt);
            }
        });
        jPanel1.add(btnMod, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void stockFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stockFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stockFieldActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        w.setVisible(true);
        w.addSqlErrorLog(this.sqlErrorLog);
        this.dispose();
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarActionPerformed
        if (checkFields()) {
            try{
                float precio = Float.parseFloat(precioField.getText());
                int stock = Integer.parseInt(stockField.getText());
                //float a = (float) stock;
                int jyes = JOptionPane.showConfirmDialog(this, "¿Estás seguro de añadir este articulo?");
                if (jyes == JOptionPane.YES_OPTION) {
                    myDB.altaArticulo(codField.getText(), 
                            descField.getText(), precio, stock);
                    JOptionPane.showMessageDialog(this, "Se ha introducido el articulo correctamente", "Check", JOptionPane.INFORMATION_MESSAGE);
                }
            }catch(NumberFormatException ex){
                JOptionPane.showMessageDialog(this, "Error al introducir los datos. Compruebe que los campos esten rellenados correctamente.", "Error", JOptionPane.ERROR_MESSAGE);
            } catch (MyException ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage());
                this.sqlErrorLog = this.sqlErrorLog + ex.getMessage();
            }   
        }
    }//GEN-LAST:event_btnEnviarActionPerformed
    
    private boolean checkFields(){
        if(codField.getText().length() > 5){
            JOptionPane.showMessageDialog(this, "El codigo de articulo puede tener como maximo 5 caracteres", "Error cod_art", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        if(descField.getText().length() > 25){
            JOptionPane.showMessageDialog(this, "El codigo de articulo puede tener como maximo 25 caracteres", "Error descripción", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        if (precioField.equals("") || codField.equals("") || descField.equals("") || stockField.equals("")) {
            JOptionPane.showConfirmDialog(this,"Ningun campo puede estar vacio", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        return true;
    }
    
    private void btnModActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModActionPerformed
        if (!precioField.isEnabled() && (!codField.getText().equals(""))) {
            try{
                String[] a = myDB.buscaArticulo(codField.getText());
                descField.setEnabled(true);
                precioField.setEnabled(true);
                stockField.setEnabled(true);
                descField.setText(a[1]);
                precioField.setText(a[2]);
                stockField.setText(a[3]);
            }catch(MyException ex){
                JOptionPane.showMessageDialog(this, ex.getMessage());
                this.sqlErrorLog = this.sqlErrorLog +  ex.getMessage();
            }
        }else if (checkFields()) {
            try{
                float precio = Float.parseFloat(precioField.getText());
                int stock = Integer.parseInt(stockField.getText());
                myDB.modificarArticulos(codField.getText(), 
                        descField.getText(), precio, stock);
                JOptionPane.showMessageDialog(this, "Los datos se han actualizado correctamente.", "Check", JOptionPane.INFORMATION_MESSAGE);
            }catch(NumberFormatException ex){
                JOptionPane.showMessageDialog(this, "Error al introducir los datos. Compruebe que los campos esten rellenados correctamente.", "Error", JOptionPane.ERROR_MESSAGE);
            } catch (MyException ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage());
                this.sqlErrorLog = this.sqlErrorLog +  ex.getMessage();
            }
        }else{
            JOptionPane.showMessageDialog(this, "Revise todos los campos.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnModActionPerformed

    private void codFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codFieldActionPerformed
        if (!precioField.isEnabled() && (!codField.getText().equals(""))) {
            try{
                String[] a = myDB.buscaArticulo(codField.getText());
                if (a!=null) {
                    descField.setEnabled(true);
                    precioField.setEnabled(true);
                    stockField.setEnabled(true);
                    descField.setText(a[1]);
                    precioField.setText(a[2]);
                    stockField.setText(a[3]);
                }else {
                    
                    JOptionPane.showMessageDialog(this, codField.getText() +   " Este artículo no existe");
                    codField.setText("");
                }
            }catch(MyException ex){
                JOptionPane.showMessageDialog(this, ex.getMessage());
                this.sqlErrorLog = this.sqlErrorLog +  ex.getMessage();
            }
        }
    }//GEN-LAST:event_codFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnviar;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnMod;
    private javax.swing.JTextField codField;
    private javax.swing.JTextField descField;
    private javax.swing.JLabel etCod;
    private javax.swing.JLabel etDesc;
    private javax.swing.JLabel etPrecio;
    private javax.swing.JLabel etStock;
    private javax.swing.JLabel etTitle;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField precioField;
    private javax.swing.JTextField stockField;
    // End of variables declaration//GEN-END:variables
}
